name: safrenz
description: "Smart door lock app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logosafrenz.svg
    - assets/images/srlogo.svg
    - assets/images/imgback.png
    - assets/images/avatar.png
    - assets/images/il_empty.svg
    - assets/images/imagekos.png
    - assets/images/onb1.png
    - assets/images/onb2.png
    - assets/images/onb3.png
    - assets/images/ktpsample.png
    - assets/images/imagedevicelock.png
    - assets/images/ic_call.svg
    - assets/images/ic_dari.svg
    - assets/images/ic_google.svg
    - assets/images/ic_apple.svg
    - assets/images/imagerequest.png
    - assets/images/qr_code_image.png
    - assets/images/succes_pay.svg
    - assets/images/menunggu_pay.svg
    - assets/images/info_pay.svg
    - assets/images/filed_pay.svg
    - assets/images/qris_logo.svg
    - assets/images/gpn_logo.svg
    - assets/images/menu_smartlock.svg
    - assets/images/menu_tenant.svg
    - assets/images/menu_lokasi.svg
    - assets/images/img_1.png
    - assets/images/img_2.png
    - assets/images/img_3.png
    - assets/images/splashlogo.png
    - assets/images/s_logo.png

  fonts:
    - family: SRIcon
      fonts:
        - asset: assets/fonts/SRIcon.ttf

#flutter_native_splash:
#  color: "#0B0020"
#  image: assets/images/s_logo.png
#  android: true
#  ios: false
#  fullscreen: true
